/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiEngineConfig {
  userAgent?: string
  enableQuic?: boolean
  enableHttp2?: boolean
  enableBrotli?: boolean
  cacheMode?: string
  cacheMaxSize?: number
  proxyUrl?: string
}
export declare function initEngine(config?: NapiEngineConfig | undefined | null): void
export interface NapiRequestConfig {
  url: string
  method?: string
  headers?: Array<Array<string>>
  body?: Buffer
  followRedirects?: boolean
  maxRedirects?: number
  disableCache?: boolean
  proxyUrl?: string
}
export interface NapiResponseHeader {
  name: string
  value: string
}
export interface NapiResponse {
  url: string
  status: number
  statusText: string
  headers: Array<NapiResponseHeader>
  body: Buffer
  redirected: boolean
  wasCached: boolean
  protocol: string
}
export declare function executeRequest(config: NapiRequestConfig): Promise<NapiResponse>
/**
 * Execute a streaming request. Returns response info immediately,
 * body chunks are delivered via the provided callback.
 */
export declare function executeStreamingRequest(config: NapiRequestConfig, onChunk: (chunk: Buffer | null, error: Error | null) => void): Promise<unknown>
